"""Initial migration

Revision ID: b1302cb13f41
Revises: 
Create Date: 2026-02-11 21:10:37.238860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1302cb13f41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('parent_job_id', sa.UUID(), nullable=True))
    op.add_column('jobs', sa.Column('generated_code', sa.Text(), nullable=True))
    op.create_index(op.f('ix_jobs_parent_job_id'), 'jobs', ['parent_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_parent_job_id'), table_name='jobs')
    op.drop_column('jobs', 'generated_code')
    op.drop_column('jobs', 'parent_job_id')
    # ### end Alembic commands ###
